### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by ibnishak** [OokTech/TW5-MultiUser#1]
Been testing your work for a few days now. Very useful. I hope you continue its development. Here are a few bugs I encountered.

- Changes made in file-system lost after refresh. Changes persist in the file, but in browser, they are not shown.
- Title changes are not transmitted from the file-system.
- Dirty indicator stays on, despite the fact that almost always changes are transmitted 

These are the one's I hope you will be able to solve in time for your release candidate. Also a minor inconvenience, rather than a bug, is the fact that if we change the location of a tiddler to a subfolder while keeping the server on, the tiddler is shown as missing. Nothing huge.

**Comment by inmysocks** [comment]
Thanks for the report!

For the moment subfolders aren't supported. There are some problems with the way that the file system supervisor works in node that I haven't worked out yet. So I am not going to support subfolders until I figure out how to get around them.

For the others I will make sure that they are on the list of things to work on when I have time.

**Comment by inmysocks** [comment]
The first problem where changes made to the file system aren't kept should be fixed at least partially. I am not sure if it is reliable or not.

I am looking into the title changes problem now.

**Comment by inmysocks** [comment]
I believe I have found where the problem that prevents title changes made on the file system from being pushed to the browsers. I will hopefully get to it this weekend.

**Comment by inmysocks** [comment]
I just pushed changes that have worked so far. I expect there to be some cases where this breaks but I haven't found any. Let me know if you run into more problems when you rename a tiddler from the file system.

**Comment by inmysocks** [comment]
I said that and then found some places where it fails. This may take a bit.

**Comment by ibnishak** [comment]
Will test it and get back to you asap.

**Comment by inmysocks** [comment]
I haven't fixed the dirty indicator yet and I still don't have the sub-folder part worked out but the other pieces should be working. I think I see how I may be able to take care of sub folders too but that may be a while.

**Comment by ibnishak** [comment]
Ok, the exciting part is - restarting the server worked flawlessly. Always wanted to do that, and kill the server from the interface

I must regretfully inform that the refresh bug is not resolved, at least not at my end (Ubuntu 16.04, Firefox 57, Node 8.4.0). Every time the browser is refreshed, text in tiddlers reverts to the condition it was when the server instance was started, while the changes are not lost in file-system. If it hit save in the file-system, changes immediately appear in the browser, but if I hit refresh again, the cycle repeats. You might want to confirm this behavior with someone else to ensure that it is not something on my settings.  


The title changes are halfway there. Now when I change the title of a tiddler in filesystem, it automatically renames the files and copies the text field correctly. However, after that the server throws up error and quits. I am attaching the error message for changing the title of "Hello.tid" to "How do we do?.tid". 


```

Deleted tiddler file Hello.tid
Delete Tiddler  /home/rzz/TiddlyWiki5/editions/MultiUserWiki/tiddlers / Hello.tid
Deleted tiddler file Hello.tid
saved file /home/rzz/TiddlyWiki5/editions/MultiUserWiki/tiddlers/How do we do_.tid
fs.js:1067
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink '/home/rzz/TiddlyWiki5/editions/MultiUserWiki/tiddlers/Hello.tid'
    at Object.fs.unlinkSync (fs.js:1067:18)
    at FSWatcher.<anonymous> ($:/plugins/OokTech/MultiUser/FileSystemMonitor.js:217:22)
    at emitTwo (events.js:125:13)
    at FSWatcher.emit (events.js:213:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1364:12)
```

In addition, the new tiddler is created as


```
created: NaNNaNNaNNaNNaNNaNNaN
title: How do we do?
tags: 
modified: NaNNaNNaNNaNNaNNaNNaN
```

**Comment by ibnishak** [comment]
I have ensured that the refresh bug is not a cache problem. I tested with cleaning the cache before refresh.

**Comment by inmysocks** [comment]
Ok. I wasn't getting that error consistently before but I thought I had fixed it. Either that or there are changes sitting on my computer at home that I forgot to push. I will see if I can fix it tonight.

**Comment by inmysocks** [comment]
I haven't been getting the problem with the date fields for a while. Are you sure that you don't have some old file in the repo?
But I did see the other errors and I found a problem in how the system was detecting changed tiddlers so it may work this time. My tests have worked but I doubt they cover everything.

**Comment by ibnishak** [comment]
> Are you sure that you don't have some old file in the repo?

I started over from step one including cloning new TW5 repo just to be sure. Here is a [screencast of the issues](https://youtu.be/-ytBAQFEFZI).

It is not a Firefox 57 issue, I checked with Opera too. If you can get someone to test in Ubuntu 16.04 and node 8.4.0 - just to eliminate the possibility that it is a platform specific issue.

**Comment by inmysocks** [comment]
I am sorry, I somehow managed to not actually push the changes that I mentioned in my last message.

But it still sounds like you may be running into another error that I am not seeing so I will look at your screen cast and try to replicate it anyway.

**Comment by inmysocks** [comment]
The dirty indicator part makes some sense now. It isn't exactly the same as in the other saver methods but it works I think.

There still isn't support for sub-folders but the rest should be ok. I will close this for now, if you see any problems leave another comment and I will reopen it.
